# Generated by Django 4.2.7 on 2026-07-23 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('rdv', 'Rendez-vous'), ('plainte', 'Plainte'), ('sos', 'Alerte SOS'), ('message', 'Message tribunal'), ('system', 'Système')], default='system', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('corps', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('lien', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
