# Generated by Django 4.2.7 on 2026-07-23 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=300)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('heures_ouverture', models.CharField(default='Lun–Ven · 08h–17h', max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tribunal',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('service', models.CharField(choices=[('civil', 'Dépôt dossier civil'), ('consultation', 'Consultation juridique'), ('audience', 'Audience correctionnelle'), ('etat_civil', 'État civil / Casier judiciaire'), ('commercial', 'Litige commercial'), ('autre', 'Autre')], max_length=30)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('rejected', 'Rejeté'), ('done', 'Effectué'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('notes_admin', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv', to=settings.AUTH_USER_MODEL)),
                ('tribunal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv', to='rdv.tribunal')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'ordering': ['-created_at'],
                'unique_together': {('tribunal', 'date', 'heure')},
            },
        ),
    ]
