# Generated by Django 4.2.7 on 2026-07-23 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteSOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('type_alerte', models.CharField(choices=[('agression', 'Agression physique'), ('vol', 'Vol / Braquage'), ('danger', 'Danger immédiat'), ('autre', 'Autre urgence')], default='danger', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('progress', 'Prise en charge'), ('resolved', 'Résolue'), ('archived', 'Archivée')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL)),
                ('pris_en_charge_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_prises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte SOS',
                'ordering': ['-created_at'],
            },
        ),
    ]
