# Generated by Django 4.2.7 on 2026-07-23 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rdv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plainte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('nature', models.CharField(choices=[('agression', 'Agression physique'), ('escroquerie', 'Escroquerie / Fraude'), ('foncier', 'Litige foncier'), ('violence', 'Violence domestique'), ('cyber', 'Cybercriminalité'), ('autre', 'Autre')], max_length=30)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('progress', 'En instruction'), ('urgent', 'Urgent'), ('done', 'Traité'), ('rejected', 'Rejeté'), ('archived', 'Archivé')], default='pending', max_length=20)),
                ('notes_greffe', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('juge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to=settings.AUTH_USER_MODEL)),
                ('plaignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaintes', to=settings.AUTH_USER_MODEL)),
                ('tribunal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaintes', to='rdv.tribunal')),
            ],
            options={
                'verbose_name': 'Plainte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='plaintes/pieces/')),
                ('nom', models.CharField(max_length=200)),
                ('taille', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('plainte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='plaintes.plainte')),
            ],
        ),
        migrations.CreateModel(
            name='MessageDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plainte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='plaintes.plainte')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
